open System.Linq
open System

let PartA = 
    [ "100 doors";
    "15 Puzzle Game";
    "2048";
    "24 game";
    "24 game/Solve";
    "4-rings or 4-squares puzzle";
    "9 billion names of God the integer";
    "99 Bottles of Beer";
    "A* search algorithm";
    "A+B";
    "ABC Problem";
    "Abstract type";
    "Abundant, deficient and perfect number classifications";
    "Accumulator factory";
    "Ackermann function";
    "Active Directory/Connect";
    "Active Directory/Search for a user";
    "Active object";
    "Addition chains";
    "Addition-chain exponentiation";
    "Address of a variable";
    "AKS test for primes";
    "Align columns";
    "Aliquot sequence classifications";
    "Almost prime";
    "Amb";
    "Amicable pairs";
    "Anagrams";
    "Anagrams/Deranged anagrams";
    "Angle difference between two bearings";
    "Animate a pendulum";
    "Animation";
    "Anonymous recursion";
    "Anti-primes";
    "Append a record to the end of a text file";
    "Apply a callback to an array";
    "Apply a digital filter (direct form II transposed)";
    "Arbitrary-precision integers (included)";
    "Archimedean spiral";
    "Arena storage pool";
    "Arithmetic evaluation";
    "Arithmetic-geometric mean";
    "Arithmetic-geometric mean/Calculate Pi";
    "Arithmetic/Complex";
    "Arithmetic/Integer";
    "Arithmetic/Rational";
    "Array concatenation";
    "Array length";
    "Arrays";
    "Aspect Oriented Programming";
    "Assertions";
    "Associative array/Creation";
    "Associative array/Iteration";
    "Atomic updates";
    "Attractive numbers";
    "Average loop length";
    "Averages/Arithmetic mean";
    "Averages/Mean angle";
    "Averages/Mean time of day";
    "Averages/Median";
    "Averages/Mode";
    "Averages/Pythagorean means";
    "Averages/Root mean square";
    "Averages/Simple moving average";
    "AVL tree";
    "Babbage problem";
    "Bacon cipher";
    "Balanced brackets";
    "Banker's algorithm";
    "Barnsley fern";
    "Base64 encode data";
    "Benford's law";
    "Bernoulli numbers";
    "Best shuffle";
    "Bilinear interpolation";
    "Binary digits";
    "Binary search";
    "Binary strings";
    "Birthday problem";
    "Bitcoin/address validation";
    "Bitcoin/public point to address";
    "Bitmap";
    "Bitmap/Bresenham's line algorithm";
    "Bitmap/Bézier curves/Cubic";
    "Bitmap/Bézier curves/Quadratic";
    "Bitmap/Flood fill";
    "Bitmap/Histogram";
    "Bitmap/Midpoint circle algorithm";
    "Bitmap/PPM conversion through a pipe";
    "Bitmap/Read a PPM file";
    "Bitmap/Read an image through a pipe";
    "Bitmap/Write a PPM file";
    "Bitwise IO";
    "Bitwise operations";
    "Boids";
    "Boolean values";
    "Box the compass";
    "Brownian tree";
    "Bulls and cows";
    "Bulls and cows/Player";
    "Burrows–Wheeler transform";
    "Caesar cipher";
    "Calculating the value of e";
    "Calendar";
    "Call a function";
    "Call a function in a shared library";
    "Canny edge detector";
    "Cantor set";
    "Card shuffles";
    "Carmichael 3 strong pseudoprimes";
    "Cartesian product of two or more lists";
    "Case-sensitivity of identifiers";
    "Catalan numbers";
    "Catalan numbers/Pascal's triangle";
    "Catamorphism";
    "Catmull–Clark subdivision surface";
    "Chaocipher";
    "Chaos game";
    "Character codes";
    "Chat server";
    "Chebyshev coefficients";
    "Check input device is a terminal";
    "Check output device is a terminal";
    "Check that file exists";
    "Checkpoint synchronization";
    "Chinese remainder theorem";
    "Chinese zodiac";
    "Cholesky decomposition";
    "Circles of given radius through two points";
    "Classes";
    "Closest-pair problem";
    "Closures/Value capture";
    "Collections";
    "Color of a screen pixel";
    "Color quantization";
    "Colour bars/Display";
    "Colour pinstripe/Display";
    "Combinations";
    "Combinations and permutations";
    "Combinations with repetitions";
    "Comma quibbling";
    "Command-line arguments";
    "Comments";
    "Compare a list of strings";
    "Compare sorting algorithms' performance";
    "Compile-time calculation";
    "Compiler/AST interpreter";
    "Compiler/code generator";
    "Compiler/lexical analyzer";
    "Compiler/syntax analyzer";
    "Compiler/virtual machine interpreter";
    "Compound data type";
    "Concurrent computing";
    "Conditional structures";
    "Conjugate transpose";
    "Constrained random points on a circle";
    "Continued fraction";
    "Continued fraction/Arithmetic/Construct from rational number";
    "Convert decimal number to rational";
    "Convert seconds to compound duration";
    "Convex hull";
    "Conway's Game of Life";
    "Copy a string";
    "Copy stdin to stdout";
    "Count in factors";
    "Count in octal";
    "Count occurrences of a substring";
    "Count the coins";
    "Cramer's rule";
    "CRC-32";
    "Create a file";
    "Create a file on magnetic tape";
    "Create a two-dimensional array at runtime";
    "Create an HTML table";
    "Create an object at a given address";
    "CSV data manipulation";
    "CSV to HTML translation";
    "Cuban primes";
    "Cumulative standard deviation";
    "Currency";
    "Currying";
    "CUSIP";
    "Cut a rectangle";
    "Cycle detection";
    "Damm algorithm";
    "Data Encryption Standard";
    "Date format";
    "Date manipulation";
    "Day of the week";
    "Deal cards for FreeCell";
    "Death Star";
    "Decision tables";
    "Deconvolution/1D";
    "Deconvolution/2D+";
    "Deepcopy";
    "Delegates";
    "Delete a file";
    "Department Numbers";
    "Detect division by zero";
    "Determinant and permanent";
    "Determine if a string is numeric";
    "Determine if only one instance is running";
    "Determine if two triangles overlap";
    "Dice game probabilities";
    "Digital root";
    "Digital root/Multiplicative digital root";
    "Dijkstra's algorithm";
    "Dinesman's multiple-dwelling problem";
    "Dining philosophers";
    "Discordian date";
    "Display a linear combination";
    "Distributed programming";
    "Diversity prediction theorem";
    "DNS query";
    "Documentation";
    "Dot product";
    "Doubly-linked list/Definition";
    "Doubly-linked list/Element definition";
    "Doubly-linked list/Element insertion";
    "Doubly-linked list/Traversal";
    "Dragon curve";
    "Draw a clock";
    "Draw a cuboid";
    "Draw a pixel";
    "Draw a rotating cube";
    "Draw a sphere";
    "Draw pixel 2";
    "Dutch national flag problem";
    "Echo server";
    "Egyptian division";
    "EKG sequence convergence";
    "Element-wise operations";
    "Elementary cellular automaton";
    "Elementary cellular automaton/Random Number Generator";
    "Elliptic curve arithmetic";
    "Elliptic Curve Digital Signature Algorithm";
    "Emirp primes";
    "Empty directory";
    "Empty program";
    "Empty string";
    "Enforced immutability";
    "Entropy";
    "Entropy/Narcissist";
    "Enumerations";
    "Environment variables";
    "Equilibrium index";
    "Ethiopian multiplication";
    "Euler method";
    "Euler's identity";
    "Euler's sum of powers conjecture";
    "Evaluate binomial coefficients";
    "Even or odd";
    "Events";
    "Evolutionary algorithm";
    "Exceptions";
    "Exceptions/Catch an exception thrown in a nested call";
    "Executable library";
    "Execute a Markov algorithm";
    "Execute a system command";
    "Execute Brain****";
    "Execute HQ9+";
    "Execute SNUSP";
    "Exponentiation operator";
    "Exponentiation order";
    "Extend your language";
    "Extensible prime generator";
    "Extract file extension";
    "Extreme floating point values";
    "Factorial";
    "Factors of a Mersenne number";
    "Factors of an integer";
    "Farey sequence";
    "Fast Fourier transform";
    "FASTA format";
    "Faulhaber's formula";
    "Faulhaber's triangle";
    "Feigenbaum constant calculation";
    "Fibonacci n-step number sequences";
    "Fibonacci sequence";
    "Fibonacci word";
    "Fibonacci word/fractal";
    "File extension is in extensions list";
    "File input/output";
    "File modification time";
    "File size";
    "File size distribution";
    "Filter";
    "Find common directory path";
    "Find first and last set bit of a long integer";
    "Find largest left truncatable prime in a given base";
    "Find limit of recursion";
    "Find palindromic numbers in both binary and ternary bases";
    "Find the intersection of a line with a plane";
    "Find the intersection of two lines";
    "Find the last Sunday of each month";
    "Find the missing permutation";
    "Finite state machine";
    "First class environments";
    "First-class functions";
    "Five weekends"; ]

let PartB =
    [ "Fivenum";
    "FizzBuzz";
    "Flatten a list";
    "Flipping bits game";
    "Flow-control structures";
    "Floyd's triangle";
    "Floyd-Warshall algorithm";
    "Forest fire";
    "Fork";
    "Formal power series";
    "Formatted numeric output";
    "Forward difference";
    "Four bit adder";
    "Fractal tree";
    "Fractran";
    "FTP";
    "Function composition";
    "Function definition";
    "Function frequency";
    "Function prototype";
    "Galton box animation";
    "Gamma function";
    "Gaussian elimination";
    "General FizzBuzz";
    "Generate Chess960 starting position";
    "Generate lower case ASCII alphabet";
    "Generate random chess position";
    "Generator/Exponential";
    "Generic swap";
    "Get system command output";
    "Globally replace text in several files";
    "Go Fish";
    "Gray code";
    "Grayscale image";
    "Greatest common divisor";
    "Greatest element of a list";
    "Greatest subsequential sum";
    "Greyscale bars/Display";
    "Guess the number";
    "Guess the number/With feedback";
    "Guess the number/With feedback (player)";
    "GUI component interaction";
    "GUI enabling/disabling of controls";
    "GUI/Maximum window dimensions";
    "Hailstone sequence";
    "Hamming numbers";
    "Handle a signal";
    "Happy numbers";
    "Harshad or Niven series";
    "Hash from two arrays";
    "Haversine formula";
    "Hello world/Graphical";
    "Hello world/Line printer";
    "Hello world/Newbie";
    "Hello world/Newline omission";
    "Hello world/Standard error";
    "Hello world/Text";
    "Hello world/Web server";
    "Here document";
    "Heronian triangles";
    "Hickerson series of almost integers";
    "Higher-order functions";
    "Hilbert curve";
    "Hofstadter Figure-Figure sequences";
    "Hofstadter Q sequence";
    "Hofstadter-Conway $10,000 sequence";
    "Holidays related to Easter";
    "Honeycombs";
    "Horizontal sundial calculations";
    "Horner's rule for polynomial evaluation";
    "Host introspection";
    "Hostname";
    "Hough transform";
    "HTTP";
    "HTTPS";
    "HTTPS/Authenticated";
    "Huffman coding";
    "I before E except after C";
    "IBAN";
    "Identity matrix";
    "Image convolution";
    "Image noise";
    "Implicit type conversion";
    "Include a file";
    "Increment a numerical string";
    "Infinity";
    "Inheritance/Single";
    "Input loop";
    "Input/Output for Lines of Text";
    "Input/Output for Pairs of Numbers";
    "Integer comparison";
    "Integer overflow";
    "Integer roots";
    "Integer sequence";
    "Introspection";
    "Inverted index";
    "Inverted syntax";
    "IPC via named pipe";
    "Iterated digits squaring";
    "Jaro distance";
    "Jensen's Device";
    "Jewels and Stones";
    "JortSort";
    "Josephus problem";
    "JSON";
    "Julia set";
    "Jump anywhere";
    "Just in time processing on a character stream";
    "K-d tree";
    "K-means++ clustering";
    "Kahan summation";
    "Kaprekar numbers";
    "Kernighans large earthquake problem";
    "Keyboard input/Flush the keyboard buffer";
    "Keyboard input/Keypress check";
    "Keyboard input/Obtain a Y or N response";
    "Keyboard macros";
    "Knapsack problem/0-1";
    "Knapsack problem/Bounded";
    "Knapsack problem/Continuous";
    "Knapsack problem/Unbounded";
    "Knight's tour";
    "Knuth shuffle";
    "Knuth's algorithm S";
    "Koch curve";
    "Kolakoski sequence";
    "Kronecker product";
    "Kronecker product based fractals";
    "Langton's ant";
    "Largest int from concatenated ints";
    "Largest number divisible by its digits";
    "Last Friday of each month";
    "Last letter-first letter";
    "Law of cosines - triples";
    "Leap year";
    "Least common multiple";
    "Left factorials";
    "Leonardo numbers";
    "Letter frequency";
    "Levenshtein distance";
    "Levenshtein distance/Alignment";
    "Linear congruential generator";
    "Linux CPU utilization";
    "List comprehensions";
    "List rooted trees";
    "Literals/Floating point";
    "Literals/Integer";
    "Literals/String";
    "Logical operations";
    "Long multiplication";
    "Long primes";
    "Longest common prefix";
    "Longest common subsequence";
    "Longest Common Substring";
    "Longest increasing subsequence";
    "Longest string challenge";
    "Look-and-say sequence";
    "Loop over multiple arrays simultaneously";
    "Loops/Break";
    "Loops/Continue";
    "Loops/Do-while";
    "Loops/Downward for";
    "Loops/For";
    "Loops/For with a specified step";
    "Loops/Foreach";
    "Loops/Increment loop index within loop body";
    "Loops/Infinite";
    "Loops/N plus one half";
    "Loops/Nested";
    "Loops/While";
    "Loops/with multiple ranges";
    "Loops/Wrong ranges";
    "LU decomposition";
    "Lucas-Lehmer test";
    "Ludic numbers";
    "Luhn test of credit card numbers";
    "LZW compression";
    "MAC Vendor Lookup";
    "Machine code";
    "Mad Libs";
    "Magic 8-Ball";
    "Magic squares of doubly even order";
    "Magic squares of odd order";
    "Magic squares of singly even order";
    "Main step of GOST 28147-89";
    "Make directory path";
    "Man or boy test";
    "Mandelbrot set";
    "Map range";
    "Matrix chain multiplication";
    "Matrix multiplication";
    "Matrix transposition";
    "Matrix-exponentiation operator";
    "Maximum triangle path sum";
    "Maze generation";
    "Maze solving";
    "McNuggets Problem";
    "MD4";
    "MD5";
    "MD5/Implementation";
    "Median filter";
    "Memory allocation";
    "Memory layout of a data structure";
    "Menu";
    "Metaprogramming";
    "Metered concurrency";
    "Metronome";
    "Mian-Chowla sequence";
    "Middle three digits";
    "Miller–Rabin primality test";
    "Minesweeper game";
    "Modular exponentiation";
    "Modular inverse";
    "Modulinos";
    "Monte Carlo methods";
    "Monty Hall problem";
    "Morpion solitaire";
    "Morse code";
    "Mouse position";
    "Move-to-front algorithm";
    "Multi-dimensional array";
    "Multifactorial";
    "Multiline shebang";
    "Multiple distinct objects";
    "Multiple regression";
    "Multiplication tables";
    "Multiplicative order";
    "Multisplit";
    "Munchausen numbers";
    "Munching squares";
    "Musical scale";
    "Mutex";
    "Mutual recursion";
    "N'th";
    "N-body problem";
    "N-queens problem";
    "Named parameters";
    "Naming conventions";
    "Narcissist";
    "Narcissistic decimal number";
    "Native shebang";
    "Natural sorting";
    "Nautical bell";
    "Negative base numbers";
    "Nested function";
    "Nim Game";
    "Non-continuous subsequences";
    "Non-decimal radices/Convert";
    "Non-decimal radices/Input";
    "Non-decimal radices/Output";
    "Nth root";
    "Null object";
    "Number names";
    "Number reversal game";
    "Numeric error propagation";
    "Numerical integration";
    "Numerical integration/Adaptive Simpson's method";
    "Numerical integration/Gauss-Legendre Quadrature";
    "Odd word problem";
    "Old lady swallowed a fly";
    "Old Russian measure of length";
    "One of n lines in a file";
    "One-dimensional cellular automata";
    "OpenGL";
    "OpenGL Pixel Shader";
    "OpenGL/Utah Teapot";
    "Operator precedence";
    "Optional parameters";
    "Orbital elements";
    "Order two numerical lists";
    "Ordered Partitions";
    "Ordered words";
    "P-value correction";
    "Palindrome detection";
    "Pangram checker";
    "Paraffins";
    "Parallel Brute Force";
    "Parallel calculations";
    "Parametric polymorphism";
    "Parametrized SQL statement";
    "Parse an IP Address";
    "Parse command-line arguments";
    "Parsing/RPN calculator algorithm";
    "Parsing/RPN to infix conversion";
    "Parsing/Shunting-yard algorithm";
    "Partial function application";
    "Pascal matrix generation";
    "Pascal's triangle";
    "Pascal's triangle/Puzzle";
    "Password generator";
    "Pathological floating point problems";
    "Peano curve";
    "Penney's game";
    "Pentagram";
    "Percentage difference between images";
    "Percolation/Bond percolation";
    "Percolation/Mean cluster density";
    "Percolation/Mean run density";
    "Percolation/Site percolation";
    "Perfect numbers"; ]

let PartC =
    [ "Perfect shuffle";
    "Perfect totient numbers";
    "Perlin noise";
    "Permutation test";
    "Permutations";
    "Permutations by swapping";
    "Permutations with repetitions";
    "Permutations/Derangements";
    "Permutations/Rank of a permutation";
    "Pernicious numbers";
    "Phrase reversals";
    "Pi";
    "Pick random element";
    "Pinstripe/Display";
    "Plasma effect";
    "Playing cards";
    "Plot coordinate pairs";
    "Pointers and references";
    "Poker hand analyser";
    "Polymorphic copy";
    "Polymorphism";
    "Polynomial long division";
    "Polynomial regression";
    "Polyspiral";
    "Population count";
    "Power set";
    "Pragmatic directives";
    "Price fraction";
    "Primality by trial division";
    "Prime decomposition";
    "Primes - allocate descendants to their ancestors";
    "Primorial numbers";
    "Priority queue";
    "Probabilistic choice";
    "Problem of Apollonius";
    "Program name";
    "Program termination";
    "Proper divisors";
    "Pythagoras tree";
    "Pythagorean quadruples";
    "Pythagorean triples";
    "QR decomposition";
    "Quaternion type";
    "Queue/Definition";
    "Queue/Usage";
    "Quickselect algorithm";
    "Quine";
    "Ramsey's theorem";
    "Random number generator (device)";
    "Random number generator (included)";
    "Random numbers";
    "Range expansion";
    "Range extraction";
    "Ranking methods";
    "Rate counter";
    "Ray-casting algorithm";
    "RCRPG";
    "Read a configuration file";
    "Read a file character by character/UTF8";
    "Read a file line by line";
    "Read a specific line from a file";
    "Read entire file";
    "Readline interface";
    "Real constants and functions";
    "Recaman's sequence";
    "Record sound";
    "Reduced row echelon form";
    "Regular expressions";
    "Remote agent/Agent interface";
    "Remote agent/Agent logic";
    "Remote agent/Simulation";
    "Remove duplicate elements";
    "Remove lines from a file";
    "Rename a file";
    "Rendezvous";
    "Rep-string";
    "Repeat";
    "Repeat a string";
    "Resistor mesh";
    "Retrieve and search chat history";
    "Return multiple values";
    "Reverse a string";
    "Reverse words in a string";
    "Rock-paper-scissors";
    "Roman numerals/Decode";
    "Roman numerals/Encode";
    "Roots of a function";
    "Roots of a quadratic function";
    "Roots of unity";
    "Rosetta Code/Rank languages by popularity";
    "Rot-13";
    "RPG Attributes Generator";
    "RSA code";
    "Run as a daemon or service";
    "Run-length encoding";
    "Runge-Kutta method";
    "S-Expressions";
    "Safe addition";
    "Sailors, coconuts and a monkey problem";
    "Same Fringe";
    "Sattolo cycle";
    "Scope modifiers";
    "Scope/Function names and labels";
    "Search a list";
    "Search a list of records";
    "Secure temporary file";
    "SEDOLs";
    "Self-describing numbers";
    "Self-referential sequence";
    "Semaphore";
    "Semiprime";
    "Semordnilap";
    "Send email";
    "Sequence of non-squares";
    "Sequence of primes by trial division";
    "Sequence of primorial primes";
    "Sequence: smallest number greater than previous term with exactly n divisors";
    "Sequence: smallest number with exactly n divisors";
    "Set";
    "Set consolidation";
    "Set of real numbers";
    "Set puzzle";
    "Seven-sided dice from five-sided dice";
    "Sexy primes";
    "SHA-1";
    "SHA-256";
    "Shell one-liner";
    "Shoelace formula for polygonal area";
    "Short-circuit evaluation";
    "Shortest common supersequence";
    "Show Ascii table";
    "Show the epoch";
    "Sierpinski carpet";
    "Sierpinski pentagon";
    "Sierpinski triangle";
    "Sierpinski triangle/Graphical";
    "Sieve of Eratosthenes";
    "Simple database";
    "Simple windowed application";
    "Simulate input/Keyboard";
    "Simulate input/Mouse";
    "Singleton";
    "Singly-linked list/Element definition";
    "Singly-linked list/Element insertion";
    "Singly-linked list/Element removal";
    "Singly-linked list/Traversal";
    "Sleep";
    "Smith numbers";
    "Snake And Ladder";
    "SOAP";
    "Sockets";
    "Sokoban";
    "Solve a Hidato puzzle";
    "Sort an array of composite structures";
    "Sort an integer array";
    "Sort disjoint sublist";
    "Sort numbers lexicographically";
    "Sort stability";
    "Sort three variables";
    "Sort using a custom comparator";
    "Sorting algorithms/Bead sort";
    "Sorting algorithms/Bogosort";
    "Sorting algorithms/Bubble sort";
    "Sorting Algorithms/Circle Sort";
    "Sorting algorithms/Cocktail sort";
    "Sorting algorithms/Comb sort";
    "Sorting algorithms/Counting sort";
    "Sorting algorithms/Cycle sort";
    "Sorting algorithms/Gnome sort";
    "Sorting algorithms/Heapsort";
    "Sorting algorithms/Insertion sort";
    "Sorting algorithms/Merge sort";
    "Sorting algorithms/Pancake sort";
    "Sorting algorithms/Patience sort";
    "Sorting algorithms/Permutation sort";
    "Sorting algorithms/Quicksort";
    "Sorting algorithms/Radix sort";
    "Sorting algorithms/Selection sort";
    "Sorting algorithms/Shell sort";
    "Sorting algorithms/Sleep sort";
    "Sorting algorithms/Stooge sort";
    "Sorting algorithms/Strand sort";
    "Soundex";
    "Sparkline in unicode";
    "Special characters";
    "Special variables";
    "Speech synthesis";
    "Spinning rod animation/Text";
    "Spiral matrix";
    "Split a character string based on change of character";
    "Spoof game";
    "SQL-based authentication";
    "Square but not cube";
    "Square-free integers";
    "Stable marriage problem";
    "Stack";
    "Stack traces";
    "Stair-climbing puzzle";
    "Start from a main routine";
    "State name puzzle";
    "Statistics/Basic";
    "Statistics/Normal distribution";
    "Stem-and-leaf plot";
    "Stern-Brocot sequence";
    "Straddling checkerboard";
    "Stream Merge";
    "String append";
    "String case";
    "String comparison";
    "String concatenation";
    "String interpolation (included)";
    "String length";
    "String matching";
    "String prepend";
    "Strip a set of characters from a string";
    "Strip block comments";
    "Strip comments from a string";
    "Strip control codes and extended characters from a string";
    "Strip whitespace from a string/Top and tail";
    "Subleq";
    "Subset sum problem";
    "Substitution Cipher";
    "Substring";
    "Substring/Top and tail";
    "Subtractive generator";
    "Sudoku";
    "Sum and product of an array";
    "Sum digits of an integer";
    "Sum multiples of 3 and 5";
    "Sum of a series";
    "Sum of squares";
    "Sum to 100";
    "Sunflower fractal";
    "Superellipse";
    "Superpermutation minimisation";
    "Sutherland-Hodgman polygon clipping";
    "Symmetric difference";
    "Synchronous concurrency";
    "System time";
    "Table creation";
    "Table creation/Postal addresses";
    "Take notes on the command line";
    "Taxicab numbers";
    "Temperature conversion";
    "Terminal control/Clear the screen";
    "Terminal control/Coloured text";
    "Terminal control/Cursor movement";
    "Terminal control/Cursor positioning";
    "Terminal control/Dimensions";
    "Terminal control/Display an extended character";
    "Terminal control/Hiding the cursor";
    "Terminal control/Inverse video";
    "Terminal control/Positional read";
    "Terminal control/Preserve screen";
    "Terminal control/Ringing the terminal bell";
    "Terminal control/Unicode output";
    "Ternary logic";
    "Test a function";
    "Test integerness";
    "Text between";
    "Text processing/1";
    "Text processing/2";
    "Text processing/Max licenses in use";
    "The ISAAC Cipher";
    "The Name Game";
    "The Twelve Days of Christmas";
    "Thiele's interpolation formula";
    "Thue-Morse";
    "Tic-tac-toe";
    "Time a function";
    "Tokenize a string";
    "Tokenize a string with escaping";
    "Top rank per group";
    "Topological sort";
    "Topological sort/Extracted top item";
    "Topswops";
    "Total circles area";
    "Totient function";
    "Towers of Hanoi";
    "Trabb Pardo–Knuth algorithm";
    "Tree traversal";
    "Trigonometric functions";
    "Truncatable primes";
    "Truncate a file";
    "Truth table";
    "Two Sum";
    "Type detection";
    "Ulam spiral (for primes)";
    "Unbias a random generator";
    "Undefined values";
    "Unicode strings";
    "Unicode variable names";
    "Universal Turing machine";
    "Unix/ls";
    "Untrusted environment";
    "Update a configuration file";
    "URL decoding";
    "URL encoding";
    "Use another language to call a function";
    "User input/Graphical";
    "User input/Text";
    "UTF-8 encode and decode";
    "Validate International Securities Identification Number";
    "Vampire number";
    "Van der Corput sequence";
    "Variable size/Get";
    "Variable size/Set";
    "Variable-length quantity";
    "Variables";
    "Variadic function";
    "Vector";
    "Vector products";
    "Verify distribution uniformity/Chi-squared test";
    "Verify distribution uniformity/Naive";
    "Vibrating rectangles";
    "Vigenère cipher";
    "Vigenère cipher/Cryptanalysis";
    "Visualize a tree";
    "VList";
    "Vogel's approximation method";
    "Voronoi diagram";
    "Walk a directory/Non-recursively";
    "Walk a directory/Recursively";
    "Water collected between towers";
    "Web scraping";
    "Welch's t-test";
    "Window creation";
    "Window creation/X11";
    "Window management";
    "Wireworld";
    "Word wrap";
    "Write entire file";
    "Write float arrays to a text file";
    "Write language name in 3D ASCII";
    "Write to Windows event log";
    "Xiaolin Wu's line algorithm";
    "XML Validation";
    "XML/DOM serialization";
    "XML/Input";
    "XML/Output";
    "XML/XPath";
    "Y combinator";
    "Yin and yang";
    "Zebra puzzle";
    "Zeckendorf number representation";
    "Zero to the zero power";
    "Zhang-Suen thinning algorithm";
    "Zig-zag matrix" ]

let Problems = Seq.ofList <| PartA@PartB@PartC

[<EntryPoint>]
let main argv = 
    Problems
        .OrderBy(fun _ ->
            Guid.NewGuid())
                .ToList()
                    .First()
                        |> Console.WriteLine
    Console.ReadLine() |> ignore
    0
