[package]
name = "shunfeng_sql_to_csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
snailquote = "0.3.1"
serde_json = "1.0.86"